<template>
    <!-- project general information  -->
    <div class="col-md-6"> 

    <b-alert show variant="light" class="col-md-12"> <b>Project Metrics</b>  <b-form-checkbox v-model="normalize" name="check-button" switch inline v-on:change="normalizeMetric($event)"> Normalize </b-form-checkbox>
    </b-alert>  
    
    <div class="control_metrics_box">
        <div class="box_title">
        Developers
        </div>
        <div class="box_value">
        {{ projectMetrics.ndevelopers }}
        </div>
    </div>

    <div class="control_metrics_box">
        <div class="box_title">
        Project Size
        </div>
        <div class="box_value">
          {{ projectMetrics.projectSize }}
        </div>
    </div>

    <div class="control_metrics_box">
        <div class="box_title">
        Project Complexity
        </div>
        <div class="box_value">
          {{ projectMetrics.projectComplexity }}
        </div>
    </div>

    <div class="control_metrics_box">
          <div class="box_title">
              Tec. Debt
          </div>
          <div class="box_value">
              {{projectMetrics.technicalDebt}}
          </div>
          <!-- <help title="Technical Debt" text="Average of Number of Technical Debt generated by Cycle." id="ba2bd83d" /> -->
      </div>


</div>
</template>
  
<script type="text/javascript">

  //import Help from '@/components/common/Help.vue'
  
  export default {
  
    name: 'ControlMetricsComponent',
  
    components: {
      //  Help
    },
    
    props:  {
       projectMetrics : { }, 
    },
  
    data() {
      return {
        normalize : false, 
      }
    },
  
    methods: {

      normalizeMetric(event){
        this.$emit("normalizeMetricEvent", event);
      }
  
    },
    
  }
  </script>
  
  <!-- Add "scoped" attribute to limit CSS to this component only -->
  <style scoped>
  
  </style>